version: '3.4'

services:
  db:
    image: mongo
    container_name: mongo-project
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=karyn
      - MONGO_INITDB_ROOT_PASSWORD=pass

  projectstudy1:
    image: projectstudy1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  